### ISSUE TITLE
When she wet herself offering her panties doesn't work

### ISSUE THREAD

**Issue by FamTroder** [FamTroder/FamMel#127]

**Comment by FamTroder** [comment]
I haven't actively fixed this, but for some reason, I can't reproduce it anymore so I'm closing it.

**Comment by Forget-About-Me2** [comment]
This is still a thing. Happened at make-out after giving her paper towels/

**Comment by Forget-About-Me2** [comment]
I really don't get this bug. I once again can't reproduce it. The code for this looks fine as well. Nothing that could even cause what I've seen.  My suspicion might be that it might be caused by a not correctly updated web page. Which does happen.

**Comment by Forget-About-Me2** [comment]
I figured it out: there were overlapping div ids. But only when the player opened the backpack while having panties
