### ISSUE TITLE
Game crashes when you go to the toilet in the bar

### ISSUE THREAD

**Issue by souvikd70** [FamTroder/FamMel#169]

**Comment by Forget-About-Me2** [comment]
First of sorry for responding so late, I apparently have not been checking my mail and GitHub lately. Secondly, I haven't been able to reproduce this in my current develop version, I haven't tried it in the version that's live. However, my changelog contains a mention of fixing a bug where it errors when you're desperate when a toilet is locked, which can happen in the bar so I'm assuming this is the same bug.
for that reason I'm marking this closed and fixed, I have updated the hosted development version to now point to the latest develop version. If the issue isn't fixed feel free to come back with more details (I.e which version you play, what the state is of the game), I'll try to pay more attention.
